sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: tidSL9SXtnZwjiVqYsPLeTj92dPQ1fA7NhKi5/rz4nUqSpEO44srequuAzCuIaQKWTNQ/9nSbvw2RGP+MD3W8WQxVNEwkuQk5PvHubNhrATd3dbKWjiNU4t+Unlfih7/zs6m9g1muuljjE3OH3GL+46coeribW/aSxmye+jv+fK0/7d8MAHwG55Oh766jM3DNTDpEFxfI1woUguwM2mr3UVejkEK2HZF9SpLFqYM8IBIYACxgcX/29GGTmJMPnFFxVd9ObegNPH+L8A3Y6DDgzMj5bYLiY2hBcJxL5RbQDfsU+483EwI12eF11AZfSRcVvClWBeYkfZpg9VAqQeSGGhzdD9Q+jvQSvYGHqA4iZ5qiPwFXVrW4GT516tbQavfIuURwmcyz2+GlnlyWtodjnAHMInbsVAUsNmRhXGTlv9so6m8ViDw4g+8964sbJr/gIwIKLXG/akuTfMR1O7j/JEwNCM2qubL70SDkP1BEiLcDD0HR0BiMTIt1NOvUMOfo4lJlV9p3Bvj5iY5GE9ojOx1dZejUwQBSBv86d3YGVRFuWEDPbegtAxahlzMqiaErJrmhKsPcCTgfBLir2Ro9uI3sNLn81WzpRl+7juRJTkAitx0l3eKX7vSXMgDKYxQh8Vl/EcP/1AfKJppY1M41uEUBGaSI7MnDR2n32USejQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Northern-Lights-Volume-2_6187
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy